# Generated by Django 5.1.7 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_map_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="map_link",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
