# Generated by Django 5.1.7 on 2026-03-26 00:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_map_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="weight_grams",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="weight_label",
            field=models.CharField(default="1 lạng (100g)", max_length=40),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="weight_multiplier",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.10"), max_digits=4),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="weight_grams",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="weight_label",
            field=models.CharField(default="1 lạng (100g)", max_length=40),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="weight_multiplier",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.10"), max_digits=4),
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_user_product_cartitem",
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("user", "product", "weight_grams"),
                name="unique_user_product_weight_cartitem",
            ),
        ),
    ]
