# Generated by Django 5.1.7 on 2026-03-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_cartitem_weight_and_orderitem_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionFacility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("manager_name", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="shop.productionzone",
                    ),
                ),
            ],
            options={
                "ordering": ["zone__province", "zone__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_order", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_steps",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "ordering": ["step_order", "id"],
            },
        ),
    ]
